version: 2

project_name: padz

builds:
  - id: padz
    main: ./cmd/padz
    binary: padz
    ldflags:

      - -s -w -X github.com/arthur-debert/padz/internal/version.Version={{.Version}} -X github.com/arthur-debert/padz/internal/version.Commit={{.Commit}} -X github.com/arthur-debert/padz/internal/version.Date={{.Date}}

    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

before:
  hooks:
    # Generate completions and man pages before archiving
    - ./scripts/gen-completion
    - ./scripts/gen-manpage

archives:
  - id: padz-archive
    ids: [padz]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "padz-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"
      - src: "completions/*"
        dst: "completions"
        info:
          mode: 0644
      - src: "man/man1/*"
        dst: "man/man1"
        info:
          mode: 0644

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

# Homebrew formula disabled until HOMEBREW_TAP_TOKEN is properly configured
# brews:
#   - ids: [padz-archive]
#     name: padz
#     repository:
#       owner: arthur-debert
#       name: homebrew-tools
#       token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
#     directory: Formula
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     homepage: "https://github.com/arthur-debert/padz"
#     description: "A simple command-line note-taking tool"
#     license: "MIT"
#     test: |
#       system "#{bin}/padz --help"
#     install: |
#       bin.install "padz"
#       
#       # Install shell completions
#       bash_completion.install "completions/padz.bash" if File.exist?("completions/padz.bash")
#       zsh_completion.install "completions/_padz" if File.exist?("completions/_padz")
#       fish_completion.install "completions/padz.fish" if File.exist?("completions/padz.fish")
#       
#       # Install man page
#       man1.install "man/man1/padz.1.gz" if File.exist?("man/man1/padz.1.gz")

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: padz
    builds: [padz]
    formats: [deb, rpm, apk]
    package_name: padz
    file_name_template: "padz_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/padz"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "A simple command-line note-taking tool"
    license: "MIT"
    section: utils
    priority: optional
    contents:
      # Man page
      - src: man/man1/padz.1.gz
        dst: /usr/share/man/man1/padz.1.gz
        file_info:
          mode: 0644
      # Bash completion
      - src: completions/padz.bash
        dst: /usr/share/bash-completion/completions/padz
        file_info:
          mode: 0644
      # Zsh completion
      - src: completions/_padz
        dst: /usr/share/zsh/site-functions/_padz
        file_info:
          mode: 0644
      # Fish completion
      - src: completions/padz.fish
        dst: /usr/share/fish/vendor_completions.d/padz.fish
        file_info:
          mode: 0644

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
