name: "TODO to Issue"
on: 
  push:
    branches: [main]

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.0
        with:
          # There is no PATH variable! Use ignore
          IGNORE: "vendor/.*"
          CLOSE_ISSUES: false
          AUTO_P: true
          # We don't auto add todo as this rarely fits the mental model when
          # writing one, these, however are more aligned with the intention
          # Use a specific label to sort them when needed 
          IDENTIFIERS: |
            [
              {"name": "FIX", "labels": ["auto-todo"]},
              {"name": "FIXME", "labels": ["auto-todo"]},
              {"name": "ISSUE", "labels": ["auto-todo"]}
            ]
